#!/bin/sh

rm bench.out
cargo build --release --features=benchmark
export ENEMY_COUNT=5000
echo ENEMY_COUNT=5000 >> bench.out
target/release/sushi_cutters enemies_bench
export ENEMY_COUNT=1000
echo ENEMY_COUNT=1000 >> bench.out
target/release/sushi_cutters enemies_bench
export ENEMY_COUNT=500
echo ENEMY_COUNT=500 >> bench.out
target/release/sushi_cutters enemies_bench
export ENEMY_COUNT=100
echo ENEMY_COUNT=100 >> bench.out
target/release/sushi_cutters enemies_bench
export ENEMY_COUNT=50
echo ENEMY_COUNT=50 >> bench.out
target/release/sushi_cutters enemies_bench
export ENEMY_COUNT=10
echo ENEMY_COUNT=10 >> bench.out
target/release/sushi_cutters enemies_bench